### PR TITLE
chore: update k8s to 1.14.2

### LINKED ISSUE #14: Update vendors
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST
 
kind feature

**What happened**:
Vendor are getting old and last update in 3 years. Can we get it updated?

**What you expected to happen**:
Updated Vendors

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by supereagle**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #14

Reference to #

**Special notes for your reviewer**:

/cc @your-reviewer

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by supereagle** [comment]
Have tested on k8s 1.14.3, and it is ok.

image

**Comment by anoopwebs** [comment]
👏

**Comment by supereagle** [comment]
> I'd say go for it, hoping that has backward compatibility at least up to 1.10

@anoopwebs  Could you help to test on the versions of kubernetes? If there is no problem, I will create a latest release.

**Comment by anoopwebs** [comment]
I can test it on 1.11 and 1.12 versions of Kubernetes but can do only tonight (EST) and will update it here.

**Comment by supereagle** [comment]
> I can test it on 1.11 and 1.12 versions of Kubernetes but can do only tonight (EST) and will update it here.

@anoopwebs  Any updates?

**Comment by anoopwebs** [comment]
@supereagle I tried building a docker image locally and run it but I got following 
```docker run -i docker run -i -p 9102:9102 -v ~/.kube/config:/root/.kube/config webs/kube-event-exporter:1.0.14 --running-in-cluster=false
Unable to find image 'docker:latest' locally
latest: Pulling from library/docker
9d48c3bd43c5: Already exists
7f94eaf8af20: Already exists
9fe9984849c1: Already exists
c20ab28a107d: Pull complete
893706d7c9c3: Pull complete
6a90931a80d1: Pull complete
f85af80e5c4b: Pull complete
Digest: sha256:2dcf87c9893b05ab815880e3d223cd6976c388a6f6697de10e90523255259ca4
Status: Downloaded newer image for docker:latest
docker: error during connect: Post http://docker:2375/v1.40/containers/create: dial tcp: lookup docker on 192.168.65.1:53: no such host.
See 'docker run --help'.

**Comment by supereagle** [comment]
I use `make docker` to build locally, what is your build command? @anoopwebs

**Comment by anoopwebs** [comment]
I used `docker build -t webs/kube-event-exporter:1.0.14 .`

**Comment by anoopwebs** [comment]
@supereagle I did verify on 1.12 Kubernetes cluster and event metrics are showing up as usual. Still, local attempt to verify is broken.

**Comment by supereagle** [comment]
> Still, local attempt to verify is broken.

Sorry, not sure about `local attempt to verify`. Do you mean that you still can not build locally by the command `docker build -t webs/kube-event-exporter:1.0.14 .`?

**Pull request merged**
