### PR TITLE
Can listen to only one namespace

### PR DESCRIPTION
**Pull request by pvalsecc**
**Release note**:

```release-note
Can now listen to only one namespace (defaults to all)
```

### CODE REVIEW

**Comment by supereagle** [comment]
@pvalsecc  Thanks for your PR. Could you share your scene?

**Comment by lichuan0620** [comment]
Basically looks good to me; just need to resolve the branch conflicts

**Comment by pvalsecc** [comment]
> Could you share your scene?

I guess you mean "why the hell do you need that?"... basically:
```
$ ./event_exporter --running-in-cluster=false --kubeconfig=$HOME/.kube/config                       
E0911 07:29:22.350004   30149 reflector.go:126] github.com/caicloud/event_exporter/store.go:111: Failed to list *v1.Event: events is forbidden: User "me" cannot list events at the cluster scope: no RBAC policy matched
```

I don't have administrative rights...

**Comment by pvalsecc** [comment]
> just need to resolve the branch conflicts

@lichuan0620,  it's done.

**Pull request merged**
